# Generated by Django 3.1.2 on 2020-10-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='member_count',
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'You'), (3, 'Unfriend'), (1, 'Confirm Friend Request'), (0, 'Pending Friend Request')], null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
