# Generated by Django 3.1.2 on 2020-11-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201029_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Confirm Friend Request'), (2, 'You'), (0, 'Pending Friend Request'), (3, 'Unfriend')], null=True),
        ),
    ]
