# Generated by Django 3.1.2 on 2020-11-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201103_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.IntegerField(blank=True, choices=[(3, 'Unfriend'), (0, 'Pending Friend Request'), (1, 'Confirm Friend Request'), (2, 'You')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_picture/'),
        ),
    ]
